### ISSUE TITLE
Error When Training Model with Custom Dataset

### ISSUE THREAD

**Issue by hoho303** [VDIGPKU/IterNet#2]
Hello. Thank you for your great work. I try to training ITerNet in VinText dataset with Vietnamese characters such as ("Ạ", "Â", "Ơ",...). Firstly, I train the language model using my own vietnamese token but got nan loss. Can you help me to fix this ?

![image](https://user-images.githubusercontent.com/31401629/164023167-dc054afe-244d-414a-b5cb-e2dac7b82230.png)

**Comment by chuxiaojie** [comment]
Hi
Our IterNet is based on language model proposed by [ABINet](https://github.com/FangShancheng/ABINet).
Some useful information about this issue can be found in FangShancheng/ABINet#13.

Besides, you can also try to train IterNet without loading pretrained language model.

**Comment by hoho303** [comment]
Thank for your response. 
I am trying to train your model without loading pretrained language model. So I will close this issue.
